apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 2
  selector:
    app: myweb
  template:
    metadata:
      app: myweb
      spec:
        containers:
          - name: myweb
            image: kubeguice/tomcat-app:v1
            ports:
              - containerPort: 8080
